------------------------------------------------------------
CREATE TABLE CLIENTES(
tid VARCHAR(10) NOT NULL,
nid NUMBER(15) NOT NULL,
nombre VARCHAR(30) NOT NULL,
correo VARCHAR(10)  NOT NULL
);

CREATE TABLE TELEFONOS(
clientesT   VARCHAR(10)  NOT NULL, 
clientesN   NUMBER(15) NOT NULL,
telefono    VARCHAR(10) NOT NULL
);

CREATE TABLE RECOMENDACIONES(
clientesT   VARCHAR(10),
clientesN   NUMBER(15) 
);


CREATE TABLE FACTURAS(
clientesT VARCHAR(10) NOT NULL,
clientesN NUMBER(15) NOT NULL,
numero INT NOT NULL,
fecha DATE  NOT NULL,
total  DECIMAL(10,2) NOT NULL
);

CREATE TABLE LINEASFACTURAS(
facturaN INT NOT NULL,
codigo NUMBER(5) NOT NULL,
cantidad NUMBER(12) NOT NULL,
precioVenta DECIMAL(10,2)  NOT NULL
);
CREATE TABLE BIENES(
CODIGO      VARCHAR(5) NOT NULL,
NOMBRE      VARCHAR(10) NOT NULL,
PRECIOVENTA     DECIMAL(10,2) NOT NULL
);

CREATE TABLE SERVICIO(
BIENESC         VARCHAR(5)  NOT NULL,
MANODEOBRA      DECIMAL(20,2) NOT NULL,
COSTO           DECIMAL(20,2) NOT NULL -- 20, 2
);

CREATE TABLE PRODUCTO(
BIENESC         VARCHAR(5) NOT NULL,
EXISTENCIAS     NUMBER(12) NOT NULL,
PRECIOCOMPRA        DECIMAL(20,2) NOT NULL
);

CREATE TABLE UTILIZA(
SERVICIOB VARCHAR(5) NOT NULL,
PRODUCTOB   VARCHAR(5) NOT NULL,
UNIDADES    NUMBER(12) NOT NULL,
PRECIOCOMPRA    DECIMAL(20,2) NOT NULL
);

CREATE TABLE PUEDEREEMPLAZAR(
PRODUCTOA   VARCHAR(5) NOT NULL,
PRODUCTOB    VARCHAR(5) NOT NULL
);





------------------------- COLOCANDO PK's -------------------------
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (tid,nid);
ALTER TABLE TELEFONOS ADD CONSTRAINT PK_TELEFONOS PRIMARY KEY (clientesT, clientesN, telefono);
ALTER TABLE RECOMENDACIONES ADD CONSTRAINT PK_RECOMENDACIONES PRIMARY KEY (clientesT, clientesN);
ALTER TABLE FACTURAS ADD CONSTRAINT PK_FACTURAS PRIMARY KEY (numero);
ALTER TABLE LINEASFACTURAS ADD CONSTRAINT PK_LINEASFACTURAS PRIMARY KEY (facturaN);
ALTER TABLE BIENES ADD CONSTRAINT PK_CODIGO PRIMARY KEY (CODIGO);
ALTER TABLE SERVICIO ADD CONSTRAINT PK_SERVICIO_B PRIMARY KEY (BIENESC);
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO_B PRIMARY KEY (BIENESC);
ALTER TABLE UTILIZA ADD CONSTRAINT PK_UTILIZA PRIMARY KEY (SERVICIOB, PRODUCTOB);
ALTER TABLE PUEDEREEMPLAZAR ADD CONSTRAINT PK_P_REEMPLAZAR PRIMARY KEY (PRODUCTOA, PRODUCTOB);



------------------------- COLOCANDO UK's -------------------------
ALTER TABLE CLIENTES ADD CONSTRAINT UK_CLIENTES UNIQUE (correo);
------------------------- COLOCANDO FK's -------------------------
ALTER TABLE TELEFONOS ADD CONSTRAINT FK_TELEFONOS_CLIENTES_clientesT_clientesN FOREIGN KEY (clientesT,clientesN) REFERENCES CLIENTES(tid,nid);
ALTER TABLE RECOMENDACIONES ADD CONSTRAINT FK_RECOMENDACIONES_CLIENTES_tclientesT_clientesN FOREIGN KEY (clientesT,clientesN) REFERENCES CLIENTES(tid,nid);

ALTER TABLE FACTURAS ADD CONSTRAINT FK_FACTURAS_CLIENTES_clientesT_clientesN FOREIGN KEY (clientesT,clientesN) REFERENCES CLIENTES(tid,nid);
ALTER TABLE LINEASFACTURAS ADD CONSTRAINT FK_LINEASFACTURAS_FACTURAS_facturaN FOREIGN KEY (facturaN) REFERENCES FACTURAS(numero);
ALTER TABLE SERVICIO ADD CONSTRAINT FK_SERVICIO_BIENES_BIENESC FOREIGN KEY (BIENESC) REFERENCES BIENES(CODIGO);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO_BIENES_BIENESC FOREIGN KEY (BIENESC) REFERENCES BIENES(CODIGO);
ALTER TABLE UTILIZA ADD CONSTRAINT FK_UTILIZA_SERVICIO_SERVICIOB FOREIGN KEY (SERVICIOB) REFERENCES SERVICIO(BIENESC);
ALTER TABLE UTILIZA ADD CONSTRAINT FK_UTILIZA_PRODUCTO_PRODUCTOC FOREIGN KEY (PRODUCTOB) REFERENCES PRODUCTO(BIENESC);
ALTER TABLE PUEDEREEMPLAZAR ADD CONSTRAINT FK_PUEDEREEMPLAZAR_PRODUCTO_PRODUCTOA FOREIGN KEY (PRODUCTOA) REFERENCES PRODUCTO(BIENESC);
ALTER TABLE PUEDEREEMPLAZAR ADD CONSTRAINT FK_PUEDEREEMPLAZAR_PRODUCTO_PRODUCTOB FOREIGN KEY (PRODUCTOB) REFERENCES PRODUCTO(BIENESC);
------------------------- TIPOS -------------------------
ALTER TABLE BIENES  ADD CONSTRAINT CK_BIENES_precioventa_Moneda CHECK (precioventa>=0 AND (MOD(precioventa, 2) = 00 OR MOD(precioventa, 2) = 00) );
ALTER TABLE CLIENTES ADD CONSTRAINT CK_CLIENTES_tid_Ttid CHECK (tid IN ('CC', 'CE', 'NT'));
ALTER TABLE TELEFONOS ADD CONSTRAINT CK_TELEFONOS_clientesT_tid CHECK (clientesT IN ('CC', 'CE', 'NT'));
ALTER TABLE RECOMENDACIONES ADD CONSTRAINT CK_RECOMENDACIONES_clientesT_Ttid CHECK (clientesT IN ('CC', 'CE', 'NT'));
ALTER TABLE FACTURAS ADD CONSTRAINT CK_FACTURAS_clientesT_Ttid CHECK (clientesT IN ('CC', 'CE', 'NT'));
ALTER TABLE CLIENTES ADD CONSTRAINT CK_CLIENTES_correo_Tcorreo CHECK (correo LIKE ('%@%'));


------------------------- CONSULTAS -------------------------
-- Consultar la informacion completa de un servicio
-- SELECT * FROM  SERVICIO;




-- X TABLAS
DROP TABLE "BD1000095256"."CLIENTES" CASCADE CONSTRAINTS PURGE;
DROP TABLE "BD1000095256"."FACTURAS" CASCADE CONSTRAINTS PURGE;
DROP TABLE "BD1000095256"."LINEASFACTURAS" CASCADE CONSTRAINTS PURGE;
DROP TABLE "BD1000095256"."BIENES" CASCADE CONSTRAINTS PURGE;
DROP TABLE "BD1000095256"."SERVICIO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "BD1000095256"."PRODUCTO" CASCADE CONSTRAINTS PURGE;
DROP TABLE "BD1000095256"."UTILIZA" CASCADE CONSTRAINTS PURGE;
DROP TABLE "BD1000095256"."PUEDEREEMPLAZAR" CASCADE CONSTRAINTS PURGE;
DROP TABLE "BD1000095256"."TELEFONOS" CASCADE CONSTRAINTS PURGE;
DROP TABLE "BD1000095256"."RECOMENDACIONES" CASCADE CONSTRAINTS PURGE;