CREATE TABLE CLIENTES(
 idCliente VARCHAR(20),
 tidCliente VARCHAR(1)
 );
 
CREATE TABLE SUSCRITOS(
clienteI VARCHAR(20),
clienteT VARCHAR(20),
nombreUsuario VARCHAR(50),
metodoPago VARCHAR(2),
nombre VARCHAR(100),
apellido VARCHAR(100)
);

CREATE TABLE RESERVAS(
clienteI VARCHAR(20),
clienteT VARCHAR(20),
idReserva VARCHAR(20),
estado CHAR(1)
);

CREATE TABLE PROVEEDORES(
articuloI VARCHAR(20),
clienteI VARCHAR(20),
clienteT VARCHAR(20),
catalogo VARCHAR(100),
correoElectronico VARCHAR(100)
);

CREATE TABLE VENTAS(
articuloI VARCHAR(20),
clienteI VARCHAR(20),
clienteT VARCHAR(20), 
idCompra VARCHAR(20),
metodoPago VARCHAR(2),
total INT,
fechaCompra DATE
);

CREATE TABLE ARTICULOS(
idArticulo VARCHAR(20),
prestamoI VARCHAR(20),
genero VARCHAR(20),
descripcion VARCHAR(100),
fechPublicacion DATE NULL
);

CREATE TABLE AUTORES(
articuloI VARCHAR(20),
autor VARCHAR(100)
);

CREATE TABLE FISICOS(
articuloI VARCHAR(20),
estado CHAR(1),
disponible CHAR(1)
);

CREATE TABLE DIGITALES(
articuloI VARCHAR(20),
formato VARCHAR(5)
);

CREATE TABLE PRESTAMOS(
clienteI VARCHAR(20),
clienteT VARCHAR(20),
idPrestamo VARCHAR(20),
reservaI VARCHAR(20),
fechaEntrega DATE,
fechaDevolucionEstimada DATE
);

CREATE TABLE DEVOLUCIONES(
prestamoI VARCHAR(20),
estado CHAR(1),
fechaDevolucion DATE
);

CREATE TABLE FACTURAS(
prestamoI VARCHAR(20),
idFactura VARCHAR(20),
metodoPago VARCHAR(2),
fecha DATE,
total INT,
estado CHAR(1)
);

CREATE TABLE MULTAS(
facturaI VARCHAR(20),
idMulta VARCHAR(20),
monto INT,
descripcion VARCHAR(100)
);


--- PRIMARY KEYS

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES
PRIMARY KEY(idCliente, tidCliente);

ALTER TABLE SUSCRITOS ADD CONSTRAINT PK_SUSCRITOS
PRIMARY KEY(ClienteI, ClienteT);

ALTER TABLE RESERVAS ADD CONSTRAINT PK_RESERVAS
PRIMARY KEY(idReserva);

ALTER TABLE PROVEEDORES ADD CONSTRAINT PK_PROVEEDORES
PRIMARY KEY(ClienteI, ClienteT);

ALTER TABLE VENTAS ADD CONSTRAINT PK_VENTAS
PRIMARY KEY(articuloI,ClienteI, ClienteT,idCompra);

ALTER TABLE ARTICULOS ADD CONSTRAINT PK_ARTICULOS
PRIMARY KEY(idArticulo);

ALTER TABLE AUTORES ADD CONSTRAINT PK_AUTORES
PRIMARY KEY(articuloI,autor);

ALTER TABLE FISICOS ADD CONSTRAINT PK_FISICOS
PRIMARY KEY(articuloI);

ALTER TABLE DIGITALES ADD CONSTRAINT PK_DIGITALES
PRIMARY KEY(articuloI);

ALTER TABLE PRESTAMOS ADD CONSTRAINT PK_PRESTAMOS
PRIMARY KEY(idPrestamo);

ALTER TABLE DEVOLUCIONES ADD CONSTRAINT PK_DEVOLUCIONES
PRIMARY KEY(PrestamoI);

ALTER TABLE FACTURAS ADD CONSTRAINT PK_FACTURAS
PRIMARY KEY(idFactura);

ALTER TABLE MULTAS ADD CONSTRAINT PK_MULTAS
PRIMARY KEY(idMulta);

---UNIQUE KEYS

ALTER TABLE SUSCRITOS ADD CONSTRAINT UK_SUSCRITOS
UNIQUE(nombreUsuario);

ALTER TABLE PROVEEDORES ADD CONSTRAINT UK_PROVEEDORES
UNIQUE(correoElectronico);

--- FOREIGN KEYS 


ALTER TABLE PROVEEDORES ADD CONSTRAINT FK_PROVEEDORES_CLIENTES_clienteI_clienteT
FOREIGN KEY(clienteI,clienteT) REFERENCES CLIENTES(idCliente,tidCliente);

ALTER TABLE PROVEEDORES ADD CONSTRAINT FK_PROVEEDORES_ARTICULOS_articuloI
FOREIGN KEY(articuloI) REFERENCES ARTICULOS(idArticulo);

ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_ARTICULOS_articuloI
FOREIGN KEY(articuloI) REFERENCES ARTICULOS(idArticulo);

ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_PROVEEDORES_clienteI_clienteT
FOREIGN KEY(clienteI,clienteT) REFERENCES PROVEEDORES(clienteI,clienteT);

ALTER TABLE SUSCRITOS ADD CONSTRAINT FK_SUSCRITOS_CLIENTES_clienteI_clienteT
FOREIGN KEY(clienteI,clienteT) REFERENCES CLIENTES(idCliente,tidCliente);

ALTER TABLE RESERVAS ADD CONSTRAINT FK_RESERVAS_SUSCRITOS_clienteI_clienteT
FOREIGN KEY(clienteI,clienteT) REFERENCES SUSCRITOS(clienteI,clienteT);

ALTER TABLE ARTICULOS ADD CONSTRAINT FK_ARTICULOS_PRESTAMOS_prestamoI
FOREIGN KEY(prestamoI) REFERENCES PRESTAMOS(idPrestamo); 

ALTER TABLE AUTORES ADD CONSTRAINT FK_AUTORES_ARTICULOS_articuloI
FOREIGN KEY(articuloI) REFERENCES ARTICULOS(idArticulo); 

ALTER TABLE FISICOS ADD CONSTRAINT FK_FISICOS_ARTICULOS_articuloI
FOREIGN KEY(articuloI) REFERENCES ARTICULOS(idArticulo); 

ALTER TABLE DIGITALES ADD CONSTRAINT FK_DIGITALES_ARTICULOS_articuloI
FOREIGN KEY(articuloI) REFERENCES ARTICULOS(idArticulo); 

ALTER TABLE PRESTAMOS ADD CONSTRAINT FK_PRESTAMOS_CLIENTES_clienteI_clienteT
FOREIGN KEY(clienteI,clienteT) REFERENCES CLIENTES(idCliente,tidCliente);

ALTER TABLE PRESTAMOS ADD CONSTRAINT FK_PRESTAMOS_RESERVAS_reservaI
FOREIGN KEY(reservaI) REFERENCES RESERVAS(idReserva);

ALTER TABLE DEVOLUCIONES ADD CONSTRAINT FK_DEVOLUCIONES_PRESTAMOS_prestamoI
FOREIGN KEY(prestamoI) REFERENCES PRESTAMOS(idPrestamo); 

ALTER TABLE FACTURAS ADD CONSTRAINT FK_FACTURAS_PRESTAMOS_prestamoI
FOREIGN KEY(prestamoI) REFERENCES PRESTAMOS(idPrestamo); 

ALTER TABLE MULTAS ADD CONSTRAINT FK_MULTAS_FACTURAS_facturaI
FOREIGN KEY(facturaI) REFERENCES FACTURAS(idFactura); 


drop table "BD1000095983"."ARTICULOS" cascade constraints PURGE;
drop table "BD1000095983"."AUTORES" cascade constraints PURGE;
drop table "BD1000095983"."CLIENTES" cascade constraints PURGE;
drop table "BD1000095983"."DEVOLUCIONES" cascade constraints PURGE;
drop table "BD1000095983"."DIGITALES" cascade constraints PURGE;
drop table "BD1000095983"."FACTURAS" cascade constraints PURGE;
drop table "BD1000095983"."MULTAS" cascade constraints PURGE;
drop table "BD1000095983"."PRESTAMOS" cascade constraints PURGE;
drop table "BD1000095983"."PROVEEDORES" cascade constraints PURGE;
drop table "BD1000095983"."RESERVAS" cascade constraints PURGE;
drop table "BD1000095983"."SUSCRITOS" cascade constraints PURGE;
drop table "BD1000095983"."VENTAS" cascade constraints PURGE;
drop table "BD1000095983"."FISICOS" cascade constraints PURGE;


